server {
    listen 80;
    server_name {{SERVER_NAME}};
    root {{DOC_ROOT}};
    client_max_body_size 64m;
    autoindex off;

    index index.php index.html;
    access_log /var/log/nginx/{{PROJECT_NAME}}.access.log;
    error_log /var/log/nginx/{{PROJECT_NAME}}.error.log;
    error_page 404 /404.php;

    location ^~ /.well-known/acme-challenge/ {
        alias {{ACME_ROOT}}/.well-known/acme-challenge/;
        default_type "text/plain";
        allow all;
    }

    location / {
        try_files $uri $uri/ /bitrix/urlrewrite.php?$args;
    }

    location ~* \.(?:css|js|gif|png|jpe?g)$ {
        expires 3d;
        try_files $uri =404;
    }

    # Bitrix hardening basics.
    location ~* /(bitrix/modules|bitrix/php_interface|bitrix/\.settings|\.settings\.php) {
        deny all;
    }

    location ~* /upload/.*\.php$ {
        deny all;
    }

    location = /healthcheck.php {
        allow 127.0.0.1;
        allow ::1;
        deny all;
        include snippets/fastcgi-php.conf;
        fastcgi_param SERVER_NAME $host;
        fastcgi_param HTTP_HOST $host;
        fastcgi_param REQUEST_SCHEME $scheme;
        fastcgi_param SERVER_PORT $server_port;
        fastcgi_param HTTPS $https if_not_empty;
        fastcgi_param HTTP_AUTHORIZATION $http_authorization;
        fastcgi_param REMOTE_USER $http_authorization;
        fastcgi_param REDIRECT_REMOTE_USER $http_authorization;
        fastcgi_pass unix:/run/php/php{{PHP_VERSION}}-fpm-{{PHP_SOCKET_PROJECT}}.sock;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_param SERVER_NAME $host;
        fastcgi_param HTTP_HOST $host;
        fastcgi_param REQUEST_SCHEME $scheme;
        fastcgi_param SERVER_PORT $server_port;
        fastcgi_param HTTPS $https if_not_empty;
        fastcgi_param HTTP_AUTHORIZATION $http_authorization;
        fastcgi_param REMOTE_USER $http_authorization;
        fastcgi_param REDIRECT_REMOTE_USER $http_authorization;
        fastcgi_pass unix:/run/php/php{{PHP_VERSION}}-fpm-{{PHP_SOCKET_PROJECT}}.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ ^/\.(?!well-known/) {
        deny all;
    }
}
